encoding: UTF-8
timezone: Asia/Shanghai
name: BillZhou233's GitHub Page
title: BillZhou233 的 GitHub Page
description: 欢迎您的到来
exclude: [README.md, .gitignore, .gitattributes]

theme: jekyll-theme-cayman

plugins:
  - jekyll-redirect-from